#define USER_SETUP_INFO "User_Setup"

#define GC9A01_DRIVER
#define TFT_WIDTH 240
#define TFT_HEIGHT 240

#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS 5
#define TFT_DC 2
#define TFT_RST 4
#define TFT_BL 15

#define TFT_SPI_FREQUENCY 40000000
#define SPI_FREQUENCY 40000000

#define LOAD_GLCD
#define LOAD_FONT2
#define LOAD_FONT4
#define LOAD_FONT6
#define LOAD_FONT7
#define LOAD_FONT8
#define LOAD_GFXFF

#define SMOOTH_FONT

#define SPI_READ_FREQUENCY 20000000
#define SPI_TOUCH_FREQUENCY 2500000

#define TFT_RGB_ORDER TFT_RGB
#define TFT_INVERSION_ON
#define TFT_ROTATION 0
#define TFT_MISO -1